default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 5
  # Force TCP connection and prevent socket lookup
  host: <%= ENV.fetch('PGHOST') { ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).hostname : nil } %>
  port: <%= ENV.fetch('PGPORT') { ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).port : nil } %>
  username: <%= ENV.fetch('PGUSER') { ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).user : nil } %>
  password: <%= ENV.fetch('PGPASSWORD') { ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).password : nil } %>
  # Explicitly disable socket connection
  socket: ""

development:
  <<: *default
  database: cmsblueprint_development

test:
  <<: *default
  database: cmsblueprint_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Additional production-specific overrides