default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 5
  # Force TCP connection explicitly
  host: <%= ENV.fetch('PGHOST', nil) %>
  port: <%= ENV.fetch('PGPORT', nil) %>
  username: <%= ENV.fetch('PGUSER', nil) %>
  password: <%= ENV.fetch('PGPASSWORD', nil) %>

development:
  <<: *default
  database: cmsblueprint_development

test:
  <<: *default
  database: cmsblueprint_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Explicitly disable socket connection
  socket: ""