default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Timeout in seconds (optional but recommended)
  connect_timeout: 5

development:
  <<: *default
  database: cmsblueprint_development
  # Uncomment if you need these locally:
  # username: your_local_username
  # password: your_local_password
  # host: localhost

test:
  <<: *default
  database: cmsblueprint_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>