default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 5

development:
  <<: *default
  database: cmsblueprint_development
  cable:
    <<: *default
    database: cmsblueprint_development

test:
  <<: *default
  database: cmsblueprint_test
  cable:
    <<: *default
    database: cmsblueprint_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Remove separate cable config since we'll use the same DB